image: ruby:2.3

pages:
  cache:
    paths:
    - vendor

  script:
  - apt-get update -yqqq
  - apt-get install -y nodejs
  - gem install bundler
  - bundle
  - npm install
  - gulp
  - bundle exec middleman build
  artifacts:
    paths:
    - build
  only:
  - bs-radio/start